apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 3
  selector:
    app: kuber
  template:
    metadata:
      name: kuber-app
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber-app-image
        image: bokovets/kuber
        ports:
        - containerPort: 8000