apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
type: Opaque
data:
  mongo-root-username: YWRtaW4= # admin (base64 encoded)
  mongo-root-password: cGFzc3dvcmQ= # password (base64 encoded)
